name: pytutor_offline
description: An offline AI-powered Python learning app with built-in compiler
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  chaquopy: ^1.4.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  flutter_code_editor: ^0.3.4
  flutter_highlighting: ^0.1.1
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/lessons/
    - assets/qa_data/
    - assets/images/
